Repository CodeAsherPlayz/Full-Login-Page, pull requests merged in 2020-12, with the labels that each got.

#2 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Pull Request

#9 Updated README.md for clarity in brackets
  README.md
Labels: Feature Request, Good First Issue, Pull Request

#11 Update README.md
  README.md
Labels: Feature Request, Good First Issue, Pull Request

#23 Update SECURITY.md due to new Versions released
  SECURITY.md
Labels: Code 2, Feature Request, Good First Issue, Issue

#25 Updated README.md for adding Javascript
  README.md
Labels: Code 2, Feature Request, Good First Issue, Issue, Pull Request

#26 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Code 2, Feature Request, Good First Issue, Issue, Pull Request

#27 Updated README.md for Version 3.0-Beta update
  README.md
Labels: Code 2, Feature Request, Good First Issue, Pull Request

#28 Delete linguist-grammars.tar.gz
  linguist-grammars.tar.gz
Labels: Code 1, Feature Request, Good First Issue, Pull Request

#29 Updated LICENSE.md for 2021
  LICENSE
Labels: Code 1, Feature Request, Good First Issue, Pull Request

#33 Updated Language Required
  CONTRIBUTING.md
Labels: Code 2, Good First Issue, Pull Request

#32 Updated Feature Request Templates
  .github/ISSUE_TEMPLATE/feature-request-template.md
Labels: Code 1, Feature Request, Good First Issue, Pull Request

#30 Updated Issue Report Templates
  .github/ISSUE_TEMPLATE/bug-report-template.md
Labels: Code 1, Feature Request, Good First Issue, Pull Request

#34 Clarity Update
  README.md
Labels: Code 2, Good First Issue, Pull Request
